language: scala
scala:
   - 2.10.5
   - 2.11.7

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2

jdk:
  - oraclejdk7
  - openjdk6

branches:
  only:
    - master

script:
  sbt ++$TRAVIS_SCALA_VERSION compile